### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by scriptcuddle** [rand-net/dribbble-py#1]
ghosteracy@cloudshell:~ (ghosteracyshell)$ drbl_py -u pokestuff
 ____   ____   ___  ____   ____   ____   _      _____         ____  __   __
|  _ \ |  _ \ |_ _|| __ ) | __ ) | __ ) | |    | ____|       |  _ \ \ \ / /
| | | || |_) | | | |  _ \ |  _ \ |  _ \ | |    |  _|   _____ | |_) | \ V /
| |_| ||  _ <  | | | |_) || |_) || |_) || |___ | |___ |_____||  __/   | |
|____/ |_| \_\|___||____/ |____/ |____/ |_____||_____|       |_|      |_|

version 0.0.1

🔍 Searching for user pokestuff...

✓ pokestuff found

Profile URL     : https://dribbble.com/pokestuff/
Shots           : 99
Projects        : 0
Collections     : 1
Liked Shots     : 54

✓ Main page scraped...
Traceback (most recent call last):
  File "/home/ghosteracy/.local/bin/drbl_py", line 8, in <module>
    sys.exit(main())
  File "/home/ghosteracy/.local/lib/python3.9/site-packages/dribbble_py/cli.py", line 101, in main
    dribbble_user.run_nursery_without_metadata_scraper()
  File "/home/ghosteracy/.local/lib/python3.9/site-packages/dribbble_py/dribbble_user.py", line 132, in run_nursery_without_metadata_scraper
    trio.run(self.scrape_user_pages_without_metadata_nursery)
  File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/ghosteracy/.local/lib/python3.9/site-packages/dribbble_py/dribbble_user.py", line 126, in scrape_user_pages_without_metadata_nursery
    nursery.start_soon(self.scrape_shots_without_metadata_page)
  File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
trio.MultiError: AttributeError("module 'httpx' has no attribute 'RequestError'"), AttributeError("module 'httpx' has no attribute 'RequestError'")

Details of embedded exception 1:

  Traceback (most recent call last):
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/dribbble_py/dribbble_user.py", line 314, in scrape_about_page
      profile_url, site = get_redirect_url(url)
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/dribbble_py/utils.py", line 33, in get_redirect_url
      response = httpx.get(
  TypeError: get() got an unexpected keyword argument 'follow_redirects'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/dribbble_py/dribbble_user.py", line 326, in scrape_about_page
      except httpx.RequestError as ex:
  AttributeError: module 'httpx' has no attribute 'RequestError'

Details of embedded exception 2:

  Traceback (most recent call last):
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpx/_client.py", line 1174, in send
      await response.aread()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpx/_models.py", line 965, in aread
      self._content = b"".join([part async for part in self.aiter_bytes()])
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpx/_models.py", line 965, in <listcomp>
      self._content = b"".join([part async for part in self.aiter_bytes()])
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpx/_models.py", line 976, in aiter_bytes
      async for chunk in self.aiter_raw():
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpx/_models.py", line 1009, in aiter_raw
      async for part in self._raw_stream:
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 49, in __aiter__
      async for chunk in self.stream:
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_async/base.py", line 57, in __aiter__
      async for chunk in self.aiterator:
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 128, in _receive_response_data
      event = await self._receive_event(timeout)
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 145, in _receive_event
      data = await self.socket.read(self.READ_NUM_BYTES, timeout)
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_backends/trio.py", line 60, in read
      async with self.read_lock:
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_sync.py", line 93, in __aenter__
      await self.acquire()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_sync.py", line 535, in acquire
      await trio.lowlevel.checkpoint_if_cancelled()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 2375, in checkpoint_if_cancelled
      await _core.checkpoint()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 2353, in checkpoint
      await _core.wait_task_rescheduled(lambda _: _core.Abort.SUCCEEDED)
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_traps.py", line 166, in wait_task_rescheduled
      return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/outcome/_impl.py", line 138, in unwrap
      raise captured_error
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 1173, in raise_cancel
      raise Cancelled._create()
  trio.Cancelled: Cancelled

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/dribbble_py/dribbble_user.py", line 532, in scrape_projects_page
      projects_page = await client.get(
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpx/_client.py", line 1305, in get
      return await self.request(
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpx/_client.py", line 1147, in request
      response = await self.send(
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpx/_client.py", line 1176, in send
      await response.aclose()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpx/_models.py", line 1031, in aclose
      await self._raw_stream.aclose()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 57, in aclose
      await self.stream.aclose()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_async/base.py", line 65, in aclose
      await self.aclose_func()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 165, in _response_closed
      await self.aclose()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 175, in aclose
      await self.socket.aclose()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/httpcore/_backends/trio.py", line 81, in aclose
      async with self.write_lock:
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_sync.py", line 93, in __aenter__
      await self.acquire()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_sync.py", line 535, in acquire
      await trio.lowlevel.checkpoint_if_cancelled()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 2375, in checkpoint_if_cancelled
      await _core.checkpoint()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 2353, in checkpoint
      await _core.wait_task_rescheduled(lambda _: _core.Abort.SUCCEEDED)
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_traps.py", line 166, in wait_task_rescheduled
      return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/outcome/_impl.py", line 138, in unwrap
      raise captured_error
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 1173, in raise_cancel
      raise Cancelled._create()
  trio.Cancelled: Cancelled

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/ghosteracy/.local/lib/python3.9/site-packages/dribbble_py/dribbble_user.py", line 662, in scrape_projects_page
      except httpx.RequestError as ex:
  AttributeError: module 'httpx' has no attribute 'RequestError'

**Comment by rand-net** [comment]
Couldn't reproduce the error. Try updating pip and reinstalling the package.
